### ISSUE TITLE
Fix FeatureStore list_entity_types() and EntityType list_features()

### ISSUE THREAD

**Issue by MichaelisTrofficus** [googleapis/python-aiplatform#1684] opened 2022-09-21 10:39 UTC
#### Environment details

  - OS type and version:
  - Python version: `3.7.12`
  - pip version: `22.2.2 `
  - `google-cloud-aiplatform` version: `1.16.1`

#### Steps to reproduce

I was trying to list the the EntityTypes and the Features created in a FeatureStore from Vertex AI Workbench (I've already detailed the Environment details). The region I built the FeatureStore into is `europe-west4`, son when I try to list the entities and the features it keeps failing (more details in the Stack Trace and Code Example).

#### Code example

```python
PROJECT_ID = "my-project"
REGION = "europe-west4"
FEATURESTORE_ID = "my_feature_store_id"

fs = FeaturestoreCustom(
    featurestore_name=FEATURESTORE_ID,
    project=PROJECT_ID,
    location=REGION,
)

fs.list_entity_types() # It fails here


entity_type = fs.get_entity_type(entity_type_id="my_entity_type_id")
entity_type.list_features() # It also fails here
```

#### Stack trace
```
InvalidArgument: 400 List of found errors:	1.Field: parent; Message: The provided location ID doesn't match the endpoint. The valid location ID is `us-central1`.	 [field_violations {
  field: "parent"
  description: "The provided location ID doesn\'t match the endpoint. The valid location ID is `us-central1`."
}
]
```

I'm going to drop a PR to solve this issue. 

Thanks in advance!!

**Comment by rosiezou** [comment] 2022-09-27 19:33
Hi @MichaelisTrofficus. Developers are encouraged to use `aiplatform.init(...)` to set global configs for project & location since it'll facilitate the rest of the development workflow. It will also resolve the error that you're seeing. You will have to manually pass in project and location for most other SDK function calls pertaining to getting or creating resources if you don't set them globally. I'm closing this issue & marking it as intended behavior.

**Closed by rosiezou** 2022-09-27 19:33 UTC
Labels: api: vertex-ai
