### ISSUE TITLE
Import error from Constants module

### ISSUE THREAD

**Issue by seraphin** [googleapis/python-aiplatform#1106] opened 2022-03-28 20:09 UTC
I have setup cloud infrastructure and using notebooks available in: https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai

When I call any module that uses utils.validate_region(location) I receive an error calling SUPPORTED_REGIONS from module 'google.cloud.aiplatform.constants'

I can recreate this behavior by executing code which exists in supporting aiplatform code:
from google.cloud.aiplatform import constants

constants.SUPPORTED_REGION
which fails
constants.base.SUPPORTED_REGION
succeeds 

#### Environment details

  - OS type and version:
 cat /etc/issue
Debian GNU/Linux 10 \n \l
Google notebook instance running Jupyter
  - Python version: `python --version`
Python 3.7.12
  - pip version: `pip --version`
pip 22.0.4 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)

  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform`
 Name: google-cloud-aiplatform
Version: 1.11.0
Summary: Vertex AI API client library
Home-page: https://github.com/googleapis/python-aiplatform
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /opt/conda/lib/python3.7/site-packages
Requires: google-api-core, google-cloud-bigquery, google-cloud-storage, packaging, proto-plus
Required-by: tfx
Note: you may need to restart the kernel to use updated packages.

#### Steps to reproduce

  1. Using example notebooks https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai
    from google.cloud.aiplatform import constants
    constants.SUPPORTED_REGION

   where 
   constants.base.SUPPORTED_REGION does work

#### Code example

from google.cloud.aiplatform import constants
constants.base

from google.cloud import aiplatform as vertex_ai

vertex_ai.init(
    project=PROJECT,
    location=REGION
)

#### Stack trace
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_15644/3064911949.py in <module>
      1 vertex_ai.init(
      2     project=PROJECT,
----> 3     location=REGION
      4 )

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/initializer.py in init(self, project, location, experiment, experiment_description, staging_bucket, credentials, encryption_spec_key_name)
     97             self._project = project
     98         if location:
---> 99             utils.validate_region(location)
    100             self._location = location
    101         if staging_bucket:

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/utils/__init__.py in validate_region(region)
    272 
    273     region = region.lower()
--> 274     if region not in constants.SUPPORTED_REGIONS:
    275         raise ValueError(
    276             f"Unsupported region for Vertex AI, select from {constants.SUPPORTED_REGIONS}"

AttributeError: module 'google.cloud.aiplatform.constants' has no attribute 'SUPPORTED_REGIONS'

```

Thanks!
David

**Comment by kweinmeister** [comment] 2022-03-29 23:56
It looks like `constants.base.SUPPORTED_REGIONS` is correct, and matches what you see here in the repo:
https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/constants/base.py#L19

I think the issue is with the example notebooks repo, that might have an older reference that has changed.

**Comment by seraphin** [comment] 2022-03-30 00:10
@kweinmeister I would say the same thing except the error is being produced by code within google.cloud.aiplatform module when calling init and specifying region and project:

example code:
from google.cloud import aiplatform as vertex_ai

vertex_ai.init(
project=PROJECT,
location=REGION
)

**Comment by morgandu** [comment] 2022-03-30 17:48
@seraphin , please see https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/initializer.py#L32

In the Vertex SDK definition, the constants' import path is `from google.cloud.aiplatform.constants import base as constants`.

The `from google.cloud.aiplatform import constants` in the notebook basically overwrite the SDK import path, and that's why it causes error.

SDK is intended to not expose all constants directly.

The quick fixing for your issue, if you have the notebooks downloaded, you can modify/remove the notebook command, and all the constants.* directly used in the notebook should be modified. So the SDK error should go away using its original import path for constants.

I can't locate which exact notebook you are using that has this error, it will be great if you can open an issue in [that repo](https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai)

**Comment by morgandu** [comment] 2022-03-30 18:25
Close this issue as it's intended behavior, feel free to reopen if there is follow up questions.

**Closed by morgandu** 2022-03-30 18:25 UTC
Labels: type: question, aiplatform, api: aiplatform
