### ISSUE TITLE
Vertex AI Matching Engine proto conflicts with google.cloud.aiplatform

### ISSUE THREAD

**Issue by SaschaHeyer** [googleapis/python-aiplatform#1447] opened 2022-06-21 08:26 UTC
Hello Google Team,

I have a Cloud Run service that's calling Vertex AI Matching Engine grpc endpoint. As soon as install `pip install google-cloud-aiplatform` and import aiplatform `from google.cloud import aiplatform` it fails with the following error message.

```
"match_service.proto": google.cloud.aiplatform.container.v1beta1.MatchRequest 
is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
```

Which makes sense because the proto files also contain the package 
`package google.cloud.aiplatform.container.v1beta1;`

package version: `google-cloud-aiplatform 1.14.0`

Any suggestions?

**Comment by SaschaHeyer** [comment] 2022-06-21 13:22
According to the protobuffer documentation adding a package directive is ignored.
https://developers.google.com/protocol-buffers/docs/proto#packages
So this also seems to be no solution here

**Comment by ivanmkc** [comment] 2022-08-11 16:09
Hi, can you try again with the latest library? We couldn't reproduce this

**Comment by MatejBabis** [comment] 2022-09-09 10:08
I think I've stumbled upon the same thing, it happens e.g. in a Jupyter notebook, where you try importing `match_service_pb2` after the `aiplatform` package:

```py
from google.cloud import aiplatform
import match_service_pb2
```
results in
```
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "match_service.proto":
  google.cloud.aiplatform.container.v1beta1.MatchRequest.deployed_index_id: "google.cloud.aiplatform.container.v1beta1.MatchRequest.deployed_index_id" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
```
and many more `... is already defined in file google/cloud/aiplatform/matching_engine/**/*.proto` errrors.

**Comment by samhedin** [comment] 2022-09-14 19:56
Also having this issue when deploying to Cloud Run.
``` 
# requirements.txt
Flask==2.2.2
gunicorn==20.1.0
grpcio-tools==1.48.1
googleapis-common-protos==1.56.4
google-cloud-aiplatform==1.17.0
```
A very standard `match.proto`:
```

syntax = "proto3";

package google.cloud.aiplatform.container.v1beta1;

import "google/rpc/status.proto";

// MatchService is a Google managed service for efficient vector similarity
// search at scale.
service MatchService {
  // Returns the nearest neighbors for the query. If it is a sharded
  // deployment, calls the other shards and aggregates the responses.
  rpc Match(MatchRequest) returns (MatchResponse) {}

  // Returns the nearest neighbors for batch queries. If it is a sharded
  // deployment, calls the other shards and aggregates the responses.
  rpc BatchMatch(BatchMatchRequest) returns (BatchMatchResponse) {}
}

// Parameters for a match query.
message MatchRequest {
  // The ID of the DeploydIndex that will serve the request.
  // This MatchRequest is sent to a specific IndexEndpoint of the Control API,
  // as per the IndexEndpoint.network. That IndexEndpoint also has
  // IndexEndpoint.deployed_indexes, and each such index has an
  // DeployedIndex.id field.
  // The value of the field below must equal one of the DeployedIndex.id
  // fields of the IndexEndpoint that is being called for this request.
  string deployed_index_id = 1;

  // The embedding values.
  repeated float float_val = 2;

  // The number of nearest neighbors to be retrieved from database for
  // each query. If not set, will use the default from
  // the service configuration.
  int32 num_neighbors = 3;

  // The list of restricts.
  repeated Namespace restricts = 4;

  // Crowding is a constraint on a neighbor list produced by nearest neighbor
  // search requiring that no more than some value k' of the k neighbors
  // returned have the same value of crowding_attribute.
  // It's used for improving result diversity.
  // This field is the maximum number of matches with the same crowding tag.
  int32 per_crowding_attribute_num_neighbors = 5;

  // The number of neighbors to find via approximate search before
  // exact reordering is performed. If not set, the default value from scam
  // config is used; if set, this value must be > 0.
  int32 approx_num_neighbors = 6;

  // The fraction of the number of leaves to search, set at query time allows
  // user to tune search performance. This value increase result in both search
  // accuracy and latency increase. The value should be between 0.0 and 1.0. If
  // not set or set to 0.0, query uses the default value specified in
  // NearestNeighborSearchConfig.TreeAHConfig.leaf_nodes_to_search_percent.
  int32 leaf_nodes_to_search_percent_override = 7;
}

// Response of a match query.
message MatchResponse {
  message Neighbor {
    // The ids of the matches.
    string id = 1;

    // The distances of the matches.
    double distance = 2;
  }
  // All its neighbors.
  repeated Neighbor neighbor = 1;
}

// Parameters for a batch match query.
message BatchMatchRequest {
  // Batched requests against one index.
  message BatchMatchRequestPerIndex {
    // The ID of the DeploydIndex that will serve the request.
    string deployed_index_id = 1;

    // The requests against the index identified by the above deployed_index_id.
    repeated MatchRequest requests = 2;

    // Selects the optimal batch size to use for low-level batching. Queries
    // within each low level batch are executed sequentially while low level
    // batches are executed in parallel.
    // This field is optional, defaults to 0 if not set. A non-positive number
    // disables low level batching, i.e. all queries are executed sequentially.
    int32 low_level_batch_size = 3;
  }

  // The batch requests grouped by indexes.
  repeated BatchMatchRequestPerIndex requests = 1;
}

// Response of a batch match query.
message BatchMatchResponse {
  // Batched responses for one index.
  message BatchMatchResponsePerIndex {
    // The ID of the DeployedIndex that produced the responses.
    string deployed_index_id = 1;

    // The match responses produced by the index identified by the above
    // deployed_index_id. This field is set only when the query against that
    // index succeed.
    repeated MatchResponse responses = 2;

    // The status of response for the batch query identified by the above
    // deployed_index_id.
    google.rpc.Status status = 3;
  }

  // The batched responses grouped by indexes.
  repeated BatchMatchResponsePerIndex responses = 1;
}

// Namespace specifies the rules for determining the datapoints that are
// eligible for each matching query, overall query is an AND across namespaces.
message Namespace {
  // The string name of the namespace that this proto is specifying,
  // such as "color", "shape", "geo", or "tags".
  string name = 1;

  // The allowed tokens in the namespace.
  repeated string allow_tokens = 2;

  // The denied tokens in the namespace.
  // The denied tokens have exactly the same format as the token fields, but
  // represents a negation. When a token is denied, then matches will be
  // excluded whenever the other datapoint has that token.
  //
  // For example, if a query specifies {color: red, blue, !purple}, then that
  // query will match datapoints that are red or blue, but if those points are
  // also purple, then they will be excluded even if they are red/blue.
  repeated string deny_tokens = 3;
}
```

And just one Python file:
``` python
# main.py
import grpc
import match_service_pb2
import match_service_pb2_grpc

from google.cloud import aiplatform
@app.route("/")
def nothing():
    return "Please"

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=int(os.environ.get("PORT", 8080)))
```

Deploying this to cloud run leads to many messages in the log referring to the collision:
```
google.cloud.aiplatform.container.v1beta1.MatchRequest.deployed_index_id: "google.cloud.aiplatform.container.v1beta1.MatchRequest.deployed_index_id" is already defined in file "match_service.proto".
```

**Comment by samhedin** [comment] 2022-09-26 12:00
I momentarily solved this by just splitting it up to two different cloud run services.
It's not a nice solution but at least it lets me progress.

**Comment by ivanmkc** [comment] 2022-11-14 20:50
Reassigning to @rosiezou for triage.

**Comment by samhedin** [comment] 2022-11-29 13:43
How is this progressing?
I fail to see how matching engine can be deployed when this issue exists, assuming you don't want to do roundabout things like splitting your service into two different projects, as I wrote about earlier.

**Comment by jaycee-li** [comment] 2022-11-30 20:14
In Vertex SDK most protos are generated from gapic. But looks like this matching engine proto is defined within SDK, and that cause the issue. I'll ask matching engine team to take a look.

**Comment by ReneeZhuGG** [comment] 2022-11-30 21:16
Hi, are you importing match_service_pb2 generated by yourself as instructed in this [notebook]( https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/matching_engine/matching_engine_for_indexing.ipynb)? 

Can you try importing the match_service_pb2 in the SDK:
```
from google.cloud.aiplatform.matching_engine._protos import match_service_pb2
from google.cloud.aiplatform.matching_engine._protos import match_service_pb2_grpc
```

We added that notebook before we imported the match service proto into this SDK and didn't realized the conflict problem.

**Comment by ReneeZhuGG** [comment] 2022-11-30 21:23
Another method you can do is to use the match method provided by the SDK: https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/matching_engine/matching_engine_index_endpoint.py#L902

However, it doesn't support filtering and crowding right now.

**Closed** 2022-12-12 20:38 UTC
Labels: :rotating_light:, triage me, api: vertex-ai
