### ISSUE TITLE
Experiment.get_data_frame() gives error "Maximum of 20 TensorboardTimeSeries to read."

### ISSUE THREAD

**Issue by simonhessner** [googleapis/python-aiplatform#3394] opened 2024-03-01 11:28 UTC
#### Environment details

  - OS type and version: Linux gcloud 5.10.0-28-cloud-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux
  - Python version: 3.10.13
  - pip version: pip 23.3.1 from /opt/conda/lib/python3.10/site-packages/pip (python 3.10)
  - `google-cloud-aiplatform` version: 1.37.0

#### Steps to reproduce

I have some VertexAI experiments (that have a tensorboard instance) and would like to access their results in a python script so that I can better group and analyze them.
The particular experiment has 15 runs and each of them contains 70 scalar metrics (I assume this is the problem here?)

This is the script I am using

#### Code example

```python
import google.cloud.aiplatform as aiplatform

aiplatform.init(
    experiment="experiment-name", project="project-name", location="us-east1"
)

print(aiplatform.Experiment().get_data_frame())

```

#### Stack trace
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 65, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.10/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "List of found errors:        1.Field: time_series; Message: Maximum of 20 TensorboardTimeSeries to read.     "
        debug_error_string = "UNKNOWN:Error received from peer ipv4:108.177.12.95:443 {created_time:"2024-03-01T11:25:16.629258575+00:00", grpc_status:3, grpc_message:"List of found errors:\t1.Field: time_series; Message: Maximum of 20 TensorboardTimeSeries to read.\t"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/get_experiment_data.py", line 7, in <module>
    print(aiplatform.Experiment("experiment-name").get_data_frame())
  File "/opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/metadata/experiment_resources.py", line 451, in get_data_frame
    ._query_experiment_row(metadata_context)
  File "/opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/metadata/experiment_run_resource.py", line 577, in _query_experiment_row
    this_experiment_run._get_latest_time_series_metric_columns()
  File "/opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/metadata/experiment_run_resource.py", line 617, in _get_latest_time_series_metric_columns
    self._backing_tensorboard_run.resource.read_time_series_data()
  File "/opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/tensorboard/tensorboard_resource.py", line 1024, in read_time_series_data
    read_response = self.api_client.batch_read_tensorboard_time_series_data(
  File "/opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform_v1/services/tensorboard_service/client.py", line 3639, in batch_read_tensorboard_time_series_data
    response = rpc(
  File "/opt/conda/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 List of found errors:   1.Field: time_series; Message: Maximum of 20 TensorboardTimeSeries to read.      [field_violations {
  field: "time_series"
  description: "Maximum of 20 TensorboardTimeSeries to read."
}
]
```

Am I using `get_data_frame` incorrectly? What is the best way to access the results of an experiment (all runs)?

**Comment by lakeyk** [comment] 2024-03-11 20:51
@simonhessner - I'm able to replicate this issue and am looking into it. You are correct - the issue is when the number of timeSeries metrics (not data points) per run exceeds 20. This should not be an issue and I will update you on a resolution.

**Comment by lakeyk** [comment] 2024-03-13 14:48
A fix for this has been submitted and should be available in the next SDK release.

**Closed by lakeyk** 2024-03-13 14:48 UTC
Labels: type: bug, priority: p1, api: vertex-ai

**Comment by lakeyk** [comment] 2024-03-15 23:20
https://github.com/googleapis/python-aiplatform/releases/tag/v1.44.0

**Comment by simonhessner** [comment] 2024-03-25 16:56
Awesome, thanks a lot!
